### ISSUE TITLE
Når der ikke er adresseoplysninger i rækken, returneres en tilfældig adresse (husnummer)

### ISSUE THREAD

**Issue by drlind** [Septima/qgis-addresstoolsdk#7]
## Når der ikke er adresseoplysninger i rækken, returneres en tilfældig adresse (husnummer)

I denne csv-fil geokodes der på en fuld adresselinje der frembringes sådan: _concat("field_2", ', ', "field_3", ' ', "field_4")_

To af de nederste rækker er tomme (datasjusk, men det er vel hvad geokoderen skal kunne klare) - alligevel foreslås en tilfældig adresse i  det pågældende postnummer. 

![image](https://user-images.githubusercontent.com/39830498/128866235-4dedeeca-d537-4271-99f6-0bfafe515c13.png)

[CW-RED_AdresserTST02.txt](https://github.com/Septima/qgis-addresstoolsdk/files/6961616/CW-RED_AdresserTST02.txt)

**Comment by AsgerPetersen** [comment]
Tak for issuet.

Det, der sker her, er, at udtrykket `concat("field_2", ', ', "field_3", ' ', "field_4")` ikke bliver `null`, hvis et eller flere fields er null. I stedet genereres en streng a la `, Holbæk` eller `, `. Pluginet prøver ikke at være klogt, det vil vi gerne overlade til DAWA, så det sender din tekst afsted, og så gætter DAWA altså på et-eller-andet.

Hvis man har felter, der er null, og ikke ønsker at DAWA skal gætte i det tilfælde, så kan man feks bruge udtrykket: `"field_2"||', '|| "field_3"|| ' '|| "field_4"`, da resultatet af dette er `null`, hvis blot et af felterne er `null`:
![image](https://user-images.githubusercontent.com/1392735/128921204-2ffe6173-ec19-4511-b3a2-52df73a5bcf2.png)

Det er nok lidt afhængigt af case, om man ønsker den ene eller anden virkemåde. Så jeg ved ikke, om vi kan ændre i vejledningen uden at gøre det unødigt kompliceret for flertallet.

**Comment by drlind** [comment]
1) Det burde nok fremgå af vores vejledning at plugin'en ikke er egnet til "snavsede" adresser

2) Dette tip burde måske nævnes i vores vejledning
`Hvis man har felter, der er null, og ikke ønsker at DAWA skal gætte i det tilfælde, så kan man feks bruge udtrykket: "field_2"||', '|| "field_3"|| ' '|| "field_4", da resultatet af dette er null, hvis blot et af felterne er null:`
