### ISSUE TITLE
Tolkning resulterer i at helt forkert adresse (husnummer) returneres

### ISSUE THREAD

**Issue by drlind** [Septima/qgis-addresstoolsdk#9]
## Tolkning resulterer i at helt forkert adresse (husnummer) returneres

Bemærkninger:
Nedenfor kan man se at de fleste solskins-adresser går godt og også nogle af de "skæve" med 12A-16 osv. 
Men:
- **Gemmas Alle 203** findes faktisk stedet returneres 202 (som ligger på den anden side af gaden)
- **Uden vejnavn, uden husnummer uden postnummer** - returnerer en helt tilfældig adresse (i et tilfældigt sted i landet)? - Se issue #7
- **Engvej 141** findes faktisk - alligevel returneres Engvej 111 (!), som ligger 1 km væk?
- **Bøge Allé 10** findes - alligevel returneres Bøge Allé 3 (!) - plus etagebetegnelse - se issue #8
- - **Gyngemose Parkvej 64** findes faktisk - i stedet returneres Sortemosevej 147 (som ligger adskillige km væk)

![image](https://user-images.githubusercontent.com/39830498/128889679-113e85c3-27b1-4251-bb81-090a9d2eefd8.png)

**Comment by AsgerPetersen** [comment]
Pluginet bruger DAWAs webservice til at vaske adresserne. Pluginet viser således blot det resultat, som webservicen returnerer. Webservicen er dog flink nok til at sætte kvaliteten til `C` for alle dine udpegede missere. Jeg synes dog også, at den nederste række burde have haft et `C`.

Det er ikke umuligt, at vi kunne bruge deres webservice bedre. Hvis du har tips eller tricks i denne retning, hører jeg dem meget gerne!

Jeg lukker issuet, da der ikke er tale om en bug i pluginet.

**Comment by cfischer00** [comment]
Vi har en adressevask funktion. Den klarer det måske bedre, tror jeg. Vi tager en snak når jeg er tilbage

**Comment by AsgerPetersen** [comment]
Det var egentlig også forkert at jeg skrev "vask" ovenfor, for det er ikke det, pluginet er bygget til. Det er bygget til geokodning. Man kan roligt sige, at det ikke lykkes at "vaske" adresserne i eksemplet :-)
